shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 6
  - npm install
  - SET PATH=C:\Ruby23-x64\bin;%PATH%
  - gem update --system
  - gem update bundler
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install
build: off
test_script: npm run-script test-only
cache: node_modules -> package.json
